# Emma Google Drive Folder Structure Setup
# Creates the required folder hierarchy in Google Drive
# Profile: ashraf.kahoush@gmail.com

Write-Host "📁 Emma Google Drive Folder Structure Creator" -ForegroundColor Cyan
Write-Host "═══════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "Profile: ashraf.kahoush@gmail.com" -ForegroundColor Yellow
Write-Host "Root: /GoogleDrive/MyDrive/AHK Profile/Emma/" -ForegroundColor Yellow
Write-Host "═══════════════════════════════════════════════`n" -ForegroundColor Cyan

Write-Host "This script will guide you through creating the folder structure.`n" -ForegroundColor White

Write-Host "📋 Required Folders:" -ForegroundColor Green
Write-Host "   /GoogleDrive/MyDrive/"
Write-Host "   └── AHK Profile/"
Write-Host "       └── Emma/"
Write-Host "           ├── KnowledgeBase/"
Write-Host "           ├── Logs/"
Write-Host "           ├── Dictionaries/"
Write-Host "           ├── Archives/"
Write-Host "           └── Outputs/  ⭐ (Primary Output)"
Write-Host ""

# Check if Google Drive is mounted locally (optional)
$possibleDrivePaths = @(
    "$env:USERPROFILE\Google Drive",
    "$env:USERPROFILE\GoogleDrive",
    "G:\My Drive",
    "G:\",
    "C:\Users\$env:USERNAME\Google Drive"
)

$foundLocalDrive = $false
$localDrivePath = $null

foreach ($path in $possibleDrivePaths) {
    if (Test-Path $path) {
        $foundLocalDrive = $true
        $localDrivePath = $path
        Write-Host "✅ Found Google Drive locally: $path" -ForegroundColor Green
        break
    }
}

if ($foundLocalDrive) {
    Write-Host "`n💡 Local Google Drive detected!" -ForegroundColor Cyan
    Write-Host "Do you want to create folders locally (will sync to cloud)? [Y/N]" -ForegroundColor Yellow
    $response = Read-Host
    
    if ($response -eq 'Y' -or $response -eq 'y') {
        $basePath = Join-Path $localDrivePath "AHK Profile\Emma"
        
        Write-Host "`n📁 Creating folder structure..." -ForegroundColor Cyan
        
        try {
            # Create base path
            if (-not (Test-Path $basePath)) {
                New-Item -ItemType Directory -Path $basePath -Force | Out-Null
                Write-Host "   ✅ Created: AHK Profile/Emma/" -ForegroundColor Green
            } else {
                Write-Host "   ℹ️  Already exists: AHK Profile/Emma/" -ForegroundColor Gray
            }
            
            # Create subfolders
            $subfolders = @("KnowledgeBase", "Logs", "Dictionaries", "Archives", "Outputs")
            
            foreach ($folder in $subfolders) {
                $folderPath = Join-Path $basePath $folder
                if (-not (Test-Path $folderPath)) {
                    New-Item -ItemType Directory -Path $folderPath -Force | Out-Null
                    Write-Host "   ✅ Created: Emma/$folder/" -ForegroundColor Green
                } else {
                    Write-Host "   ℹ️  Already exists: Emma/$folder/" -ForegroundColor Gray
                }
            }
            
            # Create README in Outputs folder
            $outputsReadme = @"
# Emma Outputs Folder

This is the **PRIMARY OUTPUT FOLDER** for Emma's generated content.

## Purpose
All Emma work products are saved here:
- Analysis reports
- Strategic recommendations
- Generated summaries
- Export files
- Voice transcripts

## Sync
- **Frequency**: Realtime
- **Permissions**: Read + Write
- **Auto-backup**: Enabled

## Last Updated
$(Get-Date -Format "yyyy-MM-dd HH:mm:ss")

---
Generated by Emma Drive Setup Script
"@
            
            $readmePath = Join-Path $basePath "Outputs\README.md"
            Set-Content -Path $readmePath -Value $outputsReadme -Force
            Write-Host "   ✅ Created: Emma/Outputs/README.md" -ForegroundColor Green
            
            Write-Host "`n✅ Folder structure created successfully!" -ForegroundColor Green
            Write-Host "   Location: $basePath" -ForegroundColor Cyan
            Write-Host "   Google Drive will sync these folders automatically.`n" -ForegroundColor Gray
            
        } catch {
            Write-Host "`n❌ Error creating folders: $_" -ForegroundColor Red
            Write-Host "Please create folders manually in Google Drive web interface.`n" -ForegroundColor Yellow
        }
    } else {
        Write-Host "`nManual creation selected. Follow the instructions below.`n" -ForegroundColor Yellow
    }
} else {
    Write-Host "`n⚠️  Local Google Drive not detected" -ForegroundColor Yellow
    Write-Host "Follow the manual instructions below.`n" -ForegroundColor Gray
}

# Manual instructions
Write-Host "═══════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "📋 Manual Creation Instructions" -ForegroundColor Cyan
Write-Host "═══════════════════════════════════════════════`n" -ForegroundColor Cyan

Write-Host "1️⃣  Open Google Drive in your browser:" -ForegroundColor White
Write-Host "   https://drive.google.com/drive/u/0/my-drive`n" -ForegroundColor Cyan

Write-Host "2️⃣  Ensure you're signed in as:" -ForegroundColor White
Write-Host "   ashraf.kahoush@gmail.com" -ForegroundColor Yellow
Write-Host "   (Check top-right profile icon)`n" -ForegroundColor Gray

Write-Host "3️⃣  Create folder structure:" -ForegroundColor White
Write-Host "   -> Right-click in My Drive -> New Folder -> 'AHK Profile'" -ForegroundColor Gray
Write-Host "   -> Open 'AHK Profile' -> New Folder -> 'Emma'" -ForegroundColor Gray
Write-Host "   -> Open 'Emma' -> Create 5 folders:" -ForegroundColor Gray
Write-Host "      • KnowledgeBase" -ForegroundColor Cyan
Write-Host "      • Logs" -ForegroundColor Cyan
Write-Host "      • Dictionaries" -ForegroundColor Cyan
Write-Host "      • Archives" -ForegroundColor Cyan
Write-Host "      • Outputs ⭐" -ForegroundColor Cyan
Write-Host ""

Write-Host "4️⃣  Verify folder structure:" -ForegroundColor White
Write-Host "   My Drive -> AHK Profile -> Emma -> [5 subfolders]`n" -ForegroundColor Gray

Write-Host "5️⃣  Test upload:" -ForegroundColor White
Write-Host "   -> Navigate to: Emma/Outputs/" -ForegroundColor Gray
Write-Host "   -> Upload any test file (e.g., test.txt)" -ForegroundColor Gray
Write-Host "   -> Verify upload completes successfully`n" -ForegroundColor Gray

Write-Host "═══════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "🚀 Next Steps" -ForegroundColor Cyan
Write-Host "═══════════════════════════════════════════════`n" -ForegroundColor Cyan

Write-Host "After creating folders in Google Drive:`n" -ForegroundColor White

Write-Host "1. Test OAuth connection:" -ForegroundColor Yellow
Write-Host "   node setup_emma_oauth.js`n" -ForegroundColor Cyan

Write-Host "2. Restart development server:" -ForegroundColor Yellow
Write-Host "   npm run dev -- --force`n" -ForegroundColor Cyan

Write-Host "3. Check Emma Drive sync:" -ForegroundColor Yellow
Write-Host "   -> Open dashboard" -ForegroundColor Cyan
Write-Host "   -> Look for Google Drive sync status" -ForegroundColor Cyan
Write-Host "   -> Verify connection to ashraf.kahoosh@gmail.com`n" -ForegroundColor Cyan

Write-Host "📖 See EMMA_DRIVE_STRUCTURE.md for full documentation`n" -ForegroundColor Gray

Write-Host "Press any key to exit..." -ForegroundColor DarkGray
$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
