/**
 * Emma Google Drive Test Upload Script
 * Tests connection and upload to Outputs folder
 * 
 * Usage: node test_emma_drive_upload.js
 */

import { google } from 'googleapis';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { getGoogleEnv, OAUTH_CONFIG } from './src/config/googleDriveConfig.js';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

console.log('🧪 Emma Google Drive Upload Test\n');
console.log('═'.repeat(70));

// Initialize OAuth2 client
const env = getGoogleEnv();

if (!env.clientId || !env.clientSecret || !env.personalRefreshToken) {
  console.log('❌ Missing OAuth credentials in .env.local');
  console.log('\nRequired variables:');
  console.log('  - VITE_GOOGLE_CLIENT_ID');
  console.log('  - VITE_GOOGLE_CLIENT_SECRET');
  console.log('  - GOOGLE_PERSONAL_REFRESH_TOKEN');
  console.log('\nRun: node setup_emma_oauth.js to configure\n');
  process.exit(1);
}

const auth = new google.auth.OAuth2(
  env.clientId,
  env.clientSecret,
  OAUTH_CONFIG.redirect_uri
);

auth.setCredentials({
  refresh_token: env.personalRefreshToken
});

const drive = google.drive({ version: 'v3', auth });

async function testConnection() {
  console.log('\n📋 Step 1: Testing Google Drive connection...');
  
  try {
    const response = await drive.about.get({ fields: 'user' });
    const user = response.data.user;
    
    console.log(`   ✅ Connected as: ${user.emailAddress}`);
    console.log(`   ✅ Display name: ${user.displayName}`);
    
    if (user.emailAddress !== 'ashraf.kahoush@gmail.com') {
      console.log(`   ⚠️  Warning: Expected ashraf.kahoush@gmail.com`);
    }
    
    return true;
  } catch (error) {
    console.log(`   ❌ Connection failed: ${error.message}`);
    return false;
  }
}

async function findEmmaFolder() {
  console.log('\n📋 Step 2: Locating Emma folder structure...');
  
  try {
    // Find AHK Profile folder
    let response = await drive.files.list({
      q: "name='AHK Profile' and mimeType='application/vnd.google-apps.folder' and trashed=false",
      fields: 'files(id, name)',
      spaces: 'drive'
    });
    
    if (!response.data.files || response.data.files.length === 0) {
      console.log('   ❌ AHK Profile folder not found');
      console.log('   → Run: powershell -ExecutionPolicy Bypass -File setup_emma_drive_folders.ps1');
      return null;
    }
    
    const ahkProfileId = response.data.files[0].id;
    console.log(`   ✅ Found: AHK Profile/ (${ahkProfileId})`);
    
    // Find Emma folder inside AHK Profile
    response = await drive.files.list({
      q: `name='Emma' and '${ahkProfileId}' in parents and mimeType='application/vnd.google-apps.folder' and trashed=false`,
      fields: 'files(id, name)',
      spaces: 'drive'
    });
    
    if (!response.data.files || response.data.files.length === 0) {
      console.log('   ❌ Emma folder not found in AHK Profile');
      return null;
    }
    
    const emmaId = response.data.files[0].id;
    console.log(`   ✅ Found: Emma/ (${emmaId})`);
    
    // Find Outputs folder inside Emma
    response = await drive.files.list({
      q: `name='Outputs' and '${emmaId}' in parents and mimeType='application/vnd.google-apps.folder' and trashed=false`,
      fields: 'files(id, name)',
      spaces: 'drive'
    });
    
    if (!response.data.files || response.data.files.length === 0) {
      console.log('   ❌ Outputs folder not found in Emma/');
      return null;
    }
    
    const outputsId = response.data.files[0].id;
    console.log(`   ✅ Found: Outputs/ (${outputsId})`);
    
    return { ahkProfileId, emmaId, outputsId };
  } catch (error) {
    console.log(`   ❌ Search failed: ${error.message}`);
    return null;
  }
}

async function uploadTestFile(folderId) {
  console.log('\n📋 Step 3: Creating test file...');
  
  const testContent = `Emma Google Drive Upload Test
  
Date: ${new Date().toISOString()}
Profile: ashraf.kahoush@gmail.com
Folder: /AHK Profile/Emma/Outputs/

This test file verifies:
✅ OAuth authentication working
✅ Folder structure accessible
✅ Write permissions enabled
✅ Upload functionality operational

Generated by: test_emma_drive_upload.js
`;
  
  const testFilePath = path.join(__dirname, 'emma_test_upload.txt');
  fs.writeFileSync(testFilePath, testContent, 'utf8');
  console.log(`   ✅ Created local test file: ${path.basename(testFilePath)}`);
  
  console.log('\n📋 Step 4: Uploading to Google Drive...');
  
  try {
    const fileMetadata = {
      name: `Emma_Test_${Date.now()}.txt`,
      parents: [folderId]
    };
    
    const media = {
      mimeType: 'text/plain',
      body: fs.createReadStream(testFilePath)
    };
    
    const response = await drive.files.create({
      requestBody: fileMetadata,
      media: media,
      fields: 'id, name, webViewLink'
    });
    
    console.log(`   ✅ Upload successful!`);
    console.log(`   ✅ File ID: ${response.data.id}`);
    console.log(`   ✅ File name: ${response.data.name}`);
    console.log(`   ✅ View link: ${response.data.webViewLink}`);
    
    // Clean up local test file
    fs.unlinkSync(testFilePath);
    console.log(`   ✅ Cleaned up local test file`);
    
    return response.data;
  } catch (error) {
    console.log(`   ❌ Upload failed: ${error.message}`);
    
    // Clean up local test file even on error
    if (fs.existsSync(testFilePath)) {
      fs.unlinkSync(testFilePath);
    }
    
    return null;
  }
}

async function verifyPermissions(folderId) {
  console.log('\n📋 Step 5: Verifying folder permissions...');
  
  try {
    const response = await drive.permissions.list({
      fileId: folderId,
      fields: 'permissions(id, type, role, emailAddress)'
    });
    
    const permissions = response.data.permissions;
    console.log(`   ✅ Found ${permissions.length} permission(s):`);
    
    permissions.forEach(perm => {
      const email = perm.emailAddress || perm.type;
      console.log(`      • ${perm.role} - ${email}`);
    });
    
    // Check for owner permission
    const hasOwner = permissions.some(p => p.role === 'owner');
    if (hasOwner) {
      console.log('   ✅ Owner permission confirmed');
      return true;
    } else {
      console.log('   ⚠️  Owner permission not found');
      return false;
    }
  } catch (error) {
    console.log(`   ❌ Permission check failed: ${error.message}`);
    return false;
  }
}

// Main execution
async function runTest() {
  console.log('Profile: ashraf.kahoush@gmail.com');
  console.log('Target: /AHK Profile/Emma/Outputs/');
  console.log('═'.repeat(70));
  
  // Test connection
  const connected = await testConnection();
  if (!connected) {
    console.log('\n❌ Test failed: Cannot connect to Google Drive\n');
    process.exit(1);
  }
  
  // Find folders
  const folders = await findEmmaFolder();
  if (!folders) {
    console.log('\n❌ Test failed: Emma folder structure not found');
    console.log('\n🚀 Action required:');
    console.log('   powershell -ExecutionPolicy Bypass -File setup_emma_drive_folders.ps1\n');
    process.exit(1);
  }
  
  // Verify permissions
  await verifyPermissions(folders.outputsId);
  
  // Upload test file
  const uploadResult = await uploadTestFile(folders.outputsId);
  
  if (!uploadResult) {
    console.log('\n❌ Test failed: Upload unsuccessful\n');
    process.exit(1);
  }
  
  // Success summary
  console.log('\n' + '═'.repeat(70));
  console.log('✅ All Tests Passed!');
  console.log('═'.repeat(70));
  console.log('\n📊 Test Summary:');
  console.log('   ✅ OAuth authentication working');
  console.log('   ✅ Connected to ashraf.kahoush@gmail.com');
  console.log('   ✅ Emma folder structure found');
  console.log('   ✅ Outputs folder accessible');
  console.log('   ✅ Write permissions enabled');
  console.log('   ✅ Test file uploaded successfully');
  
  console.log('\n🎉 Emma Google Drive sync is ready!');
  console.log('\n🚀 Next Steps:');
  console.log('   1. Restart dev server: npm run dev -- --force');
  console.log('   2. Check dashboard for Drive sync status');
  console.log('   3. Monitor Emma logs for sync activity\n');
}

runTest().catch(error => {
  console.error('\n❌ Unexpected error:', error);
  process.exit(1);
});
