// ...existing code...
import { Target, Rocket, TrendingUp, DollarSign, CheckCircle, Clock } from 'lucide-react'
import { useState } from 'react'
import MetricCard from '../components/MetricCard'
import ProjectCard from '../components/ProjectCard'
import { useProjects, useRoadmap } from '../utils/useData'
import metricsData from '../data/metrics.json'

export default function Dashboard() {
  const { overview, projectHealth, timeline} = metricsData
  const projects = useProjects()
  const roadmap = useRoadmap()
  
  // UI feedback state
  const [reportLoading, setReportLoading] = useState(false)
  const [analysisLoading, setAnalysisLoading] = useState(false)
  const [message, setMessage] = useState('')
  const [messageType, setMessageType] = useState('success') // 'success' | 'error'

  async function handleGenerateReport() {
    setReportLoading(true)
    setMessage('')
    
    try {
      console.log('🚀 Initiating report generation...')
      
      const response = await fetch('/api/generate-report', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          format: 'pdf',
          includeCharts: true,
          sections: [
            'Executive Summary',
            'Portfolio Overview',
            'Financial Metrics',
            'Project Progress',
            'AI Insights',
            'Risk Analysis',
            'Strategic Recommendations'
          ]
        })
      })
      
      const data = await response.json()
      
      if (data.success) {
        console.log('✅ Report generation successful:', data.report)
        
        // Save report to Emma KnowledgeBase
        try {
          const reportContent = `# ${data.report.title}

**Generated:** ${new Date(data.report.generatedAt).toLocaleString()}
**Format:** ${data.report.format}
**Confidentiality:** ${data.report.metadata.confidentiality}

---

## Executive Summary

${data.report.summary ? `
- **Total Projects:** ${data.report.summary.totalProjects}
- **Active Projects:** ${data.report.summary.activeProjects}
- **Completion Rate:** ${data.report.summary.completionRate}
- **Total Budget:** ${data.report.summary.totalBudget}
- **Projected ROI:** ${data.report.summary.projectedROI}
` : 'Summary data unavailable'}

---

## Sections Included

${data.report.sections.map(section => `- ${section}`).join('\n')}

---

## Report Details

This report was automatically generated by the AHK Strategic Command Center.

**Charts Included:** ${data.report.charts ? 'Yes' : 'No'}

---

*Report Version: ${data.report.metadata.version}*
`;

          const saveResponse = await fetch('/api/save-report', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              title: data.report.title,
              content: reportContent
            })
          });

          const saveData = await saveResponse.json();
          
          if (saveData.success) {
            console.log('💾 Report saved to archive:', saveData.filename);
            setMessage(`Report ready 🎉 - ${data.report.sections.length} sections, Saved to archive ✅`);
          } else {
            console.warn('⚠️ Report generated but not saved:', saveData.error);
            setMessage(`Report ready 🎉 - ${data.report.sections.length} sections (archive save failed)`);
          }
        } catch (saveError) {
          console.error('❌ Failed to save report:', saveError);
          setMessage(`Report ready 🎉 - ${data.report.sections.length} sections (archive save failed)`);
        }
        
        setMessageType('success')
        
        // Auto-clear message after 8 seconds
        setTimeout(() => setMessage(''), 8000)
      } else {
        console.error('❌ Report generation failed:', data)
        setMessage('Failed to generate report ❌')
        setMessageType('error')
      }
    } catch (error) {
      console.error('❌ Report generation error:', error)
      setMessage('Error generating report. Check console for details.')
      setMessageType('error')
    } finally {
      setReportLoading(false)
    }
  }

  async function handleRunAnalysis() {
    setAnalysisLoading(true)
    setMessage('')
    
    try {
      console.log('🤖 Initiating AI analysis...')
      
      // Log to API and get results
      const response = await fetch('/api/run-analysis', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          analysisType: 'full',
          trigger: 'dashboard-button'
        })
      })
      
      const data = await response.json()
      
      if (data.success) {
        console.log('✅ Analysis complete:', data.results)
        setMessage(`Analysis complete 🤖 - ${data.results.insights.length} insights, ${data.results.recommendations.length} recommendations`)
        setMessageType('success')
        
        // Then trigger the actual AI Co-Pilot panel
        window.dispatchEvent(new CustomEvent('runCoPilotAnalysis'))
        
        // Auto-clear message after 8 seconds
        setTimeout(() => setMessage(''), 8000)
      } else {
        console.error('❌ Analysis failed:', data)
        setMessage('Analysis failed ❌')
        setMessageType('error')
      }
    } catch (error) {
      console.error('❌ Analysis trigger error:', error)
      setMessage('Error running analysis. Check console for details.')
      setMessageType('error')
      
      // Still dispatch event even if logging fails
      window.dispatchEvent(new CustomEvent('runCoPilotAnalysis'))
    } finally {
      setAnalysisLoading(false)
    }
  }

  return (
    <div className="space-y-8 page-transition">
      {/* Feedback Message */}
      {message && (
        <div 
          className={`relative overflow-hidden rounded-2xl backdrop-blur-xl border-2 shadow-2xl animate-slide-in ${
            messageType === 'success' 
              ? 'bg-gradient-to-r from-ahk-green-500/20 to-emerald-500/20 border-ahk-green-500/60' 
              : 'bg-gradient-to-r from-red-500/20 to-rose-500/20 border-red-500/60'
          }`}
        >
          <div className="absolute inset-0 bg-gradient-to-br from-white/5 to-transparent"></div>
          <div className="relative z-10 p-5 flex items-center justify-between">
            <p className={`font-display font-bold text-lg ${
              messageType === 'success' ? 'text-ahk-green-300' : 'text-red-300'
            }`}>
              {message}
            </p>
            <button 
              onClick={() => setMessage('')}
              className="text-white/70 hover:text-white text-2xl font-bold transition-colors hover:scale-110 duration-300"
            >
              ×
            </button>
          </div>
        </div>
      )}

      {/* Premium Page Header */}
      <div className="relative">
        {/* Background Glow */}
        <div className="absolute -top-20 -left-20 w-64 h-64 bg-ahk-gold-500/10 rounded-full blur-3xl"></div>
        
        <div className="relative flex items-center justify-between">
          <div>
            <h1 className="text-5xl font-display font-black text-gradient-gold mb-2 animate-fade-in-down">
              Strategic Dashboard
            </h1>
            <p className="text-lg text-ahk-slate-200 font-sans tracking-wide flex items-center gap-2 animate-fade-in-up">
              <span className="inline-block w-2 h-2 bg-ahk-green-500 rounded-full animate-glow-pulse"></span>
              Your command center for AHK Strategies growth
            </p>
          </div>
          <button 
            onClick={handleGenerateReport}
            disabled={reportLoading}
            className="btn-primary disabled:opacity-50 disabled:cursor-not-allowed flex items-center space-x-3 px-8 py-4 text-lg shadow-gold-lg hover:shadow-gold-xl transition-all duration-300 hover:scale-105"
          >
            {reportLoading ? (
              <>
                <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-ahk-navy-900"></div>
                <span className="font-display font-bold">Generating...</span>
              </>
            ) : (
              <>
                <Rocket className="w-5 h-5" />
                <span className="font-display font-bold">Generate Report</span>
              </>
            )}
          </button>
        </div>
      </div>

      {/* Key Metrics Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <MetricCard
          title="Active Projects"
          value={overview.activeProjects}
          change="+1 this month"
          trend="up"
          icon={Rocket}
          color="navy"
        />
        <MetricCard
          title="Tasks Completed"
          value={`${overview.completedTasks}/${overview.totalTasks}`}
          change={`${Math.round((overview.completedTasks / overview.totalTasks) * 100)}%`}
          trend="up"
          icon={CheckCircle}
          color="gold"
        />
        <MetricCard
          title="Projected ROI"
          value={overview.projectedROI}
          change="+15% vs target"
          trend="up"
          icon={TrendingUp}
          color="slate"
        />
        <MetricCard
          title="Total Budget"
          value={overview.totalBudget}
          change="On track"
          trend="up"
          icon={DollarSign}
          color="navy"
        />
      </div>

      {/* Timeline Alert */}
      <div className="relative group overflow-hidden rounded-2xl bg-gradient-to-r from-ahk-gold-500 to-ahk-gold-400 p-8 shadow-gold-xl hover:shadow-gold-2xl transition-all duration-500 cursor-pointer">
        {/* Animated Background Pattern */}
        <div className="absolute inset-0 opacity-10">
          <div className="absolute top-0 right-0 w-64 h-64 bg-white rounded-full blur-3xl transform translate-x-1/2 -translate-y-1/2 group-hover:scale-150 transition-transform duration-700"></div>
        </div>
        
        <div className="relative z-10 flex items-center justify-between">
          <div className="flex items-center space-x-5">
            <div className="relative">
              <div className="absolute inset-0 bg-white/30 rounded-xl blur-xl animate-glow-pulse"></div>
              <div className="relative bg-white/20 backdrop-blur-sm rounded-xl p-4 border border-white/30 group-hover:scale-110 transition-transform duration-300">
                <Clock className="w-8 h-8 text-white" strokeWidth={2.5} />
              </div>
            </div>
            <div>
              <h3 className="text-2xl font-display font-black text-ahk-navy-900 mb-1">Next Milestone</h3>
              <p className="text-ahk-navy-800 font-sans text-lg">
                {timeline.nextMilestone} - <span className="font-display font-bold">{timeline.daysToNextMilestone} days</span> remaining
              </p>
            </div>
          </div>
          <div className="text-right bg-white/20 backdrop-blur-sm rounded-xl px-6 py-4 border border-white/30">
            <p className="text-sm text-ahk-navy-700 font-sans uppercase tracking-wider mb-1">Current Phase</p>
            <p className="text-2xl font-display font-black text-ahk-navy-900">{timeline.currentPhase}</p>
          </div>
        </div>
      </div>

      {/* Projects Section */}
      <div>
        <div className="flex items-center justify-between mb-6">
          <div>
            <h2 className="text-3xl font-display font-black text-gradient-electric mb-2">
              Active Projects
            </h2>
            <p className="text-sm text-ahk-slate-300 font-sans">Strategic initiatives driving AHK forward</p>
          </div>
          <div className="flex items-center space-x-6 text-sm bg-ahk-navy-600/50 backdrop-blur-sm rounded-xl px-6 py-3 border border-ahk-gold-500/20">
            <span className="flex items-center space-x-2">
              <span className="w-3 h-3 bg-green-500 rounded-full shadow-lg shadow-green-500/50 animate-glow-pulse"></span>
              <span className="text-ahk-slate-200 font-sans"><span className="font-display font-bold text-ahk-green-400">{projectHealth.onTrack}</span> On Track</span>
            </span>
            <span className="w-px h-6 bg-ahk-gold-500/20"></span>
            <span className="flex items-center space-x-2">
              <span className="w-3 h-3 bg-blue-500 rounded-full shadow-lg shadow-blue-500/50"></span>
              <span className="text-ahk-slate-200 font-sans"><span className="font-display font-bold text-ahk-blue-400">{projectHealth.planning}</span> Planning</span>
            </span>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {projects.map((project) => (
            <ProjectCard key={project.id} project={project} />
          ))}
        </div>
      </div>

      {/* Quick Actions */}
      <div className="relative overflow-hidden rounded-2xl bg-gradient-to-br from-ahk-navy-600/50 to-ahk-navy-700/50 backdrop-blur-xl border border-ahk-gold-500/30 shadow-2xl p-8">
        {/* Background Glow */}
        <div className="absolute top-0 right-0 w-96 h-96 bg-ahk-gold-500/5 rounded-full blur-3xl"></div>
        
        <div className="relative z-10">
          <h3 className="text-2xl font-display font-black text-gradient-gold mb-6">
            Quick Actions
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-3 gap-5">
            <button className="group relative overflow-hidden flex items-center space-x-4 p-5 bg-ahk-navy-600/40 border-2 border-ahk-gold-500/30 hover:border-ahk-gold-500/60 rounded-xl hover:bg-ahk-navy-500/50 transition-all duration-300 hover:scale-105 shadow-lg hover:shadow-gold-md">
              <div className="absolute inset-0 bg-gradient-to-br from-ahk-gold-500/10 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>
              <div className="relative bg-gradient-to-br from-ahk-navy-500/60 to-ahk-navy-600/60 rounded-lg p-3 border border-ahk-gold-500/30 group-hover:scale-110 transition-transform duration-300">
                <Target className="w-6 h-6 text-ahk-gold-400" strokeWidth={2} />
              </div>
              <span className="relative font-display font-bold text-white group-hover:text-ahk-gold-300 transition-colors">Update Roadmap</span>
            </button>
            
            <button 
              onClick={handleRunAnalysis}
              disabled={analysisLoading}
              data-run-ai-analysis
              className="group relative overflow-hidden flex items-center space-x-4 p-5 bg-ahk-navy-600/40 border-2 border-ahk-gold-500/30 hover:border-ahk-gold-500/60 rounded-xl hover:bg-ahk-navy-500/50 transition-all duration-300 hover:scale-105 shadow-lg hover:shadow-gold-md cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed disabled:hover:scale-100"
            >
              <div className="absolute inset-0 bg-gradient-to-br from-ahk-gold-500/10 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>
              {analysisLoading ? (
                <>
                  <div className="relative">
                    <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-ahk-gold-400"></div>
                  </div>
                  <span className="relative font-display font-bold text-white">Analyzing...</span>
                </>
              ) : (
                <>
                  <div className="relative bg-gradient-to-br from-ahk-gold-500/60 to-ahk-gold-600/60 rounded-lg p-3 border border-ahk-gold-500/50 group-hover:scale-110 transition-transform duration-300 shadow-gold-md">
                    <TrendingUp className="w-6 h-6 text-white" strokeWidth={2.5} />
                  </div>
                  <span className="relative font-display font-bold text-white group-hover:text-ahk-gold-300 transition-colors">Run AI Analysis</span>
                </>
              )}
            </button>
            
            <button className="group relative overflow-hidden flex items-center space-x-4 p-5 bg-ahk-navy-600/40 border-2 border-ahk-gold-500/30 hover:border-ahk-gold-500/60 rounded-xl hover:bg-ahk-navy-500/50 transition-all duration-300 hover:scale-105 shadow-lg hover:shadow-gold-md">
              <div className="absolute inset-0 bg-gradient-to-br from-ahk-gold-500/10 to-transparent opacity-0 group-hover:opacity-100 transition-opacity duration-300"></div>
              <div className="relative bg-gradient-to-br from-ahk-navy-500/60 to-ahk-navy-600/60 rounded-lg p-3 border border-ahk-gold-500/30 group-hover:scale-110 transition-transform duration-300">
                <Rocket className="w-6 h-6 text-ahk-gold-400" strokeWidth={2} />
              </div>
              <span className="relative font-display font-bold text-white group-hover:text-ahk-gold-300 transition-colors">Export Report</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  )
}
