import { Target, Rocket, TrendingUp, DollarSign, CheckCircle, Clock } from 'lucide-react'
import { useState } from 'react'
import MetricCard from '../components/MetricCard'
import ProjectCard from '../components/ProjectCard'
import { useProjects, useRoadmap } from '../utils/useData'
import metricsData from '../data/metrics.json'

export default function Dashboard() {
  const { overview, projectHealth, timeline} = metricsData
  const projects = useProjects()
  const roadmap = useRoadmap()
  
  // UI feedback state
  const [reportLoading, setReportLoading] = useState(false)
  const [analysisLoading, setAnalysisLoading] = useState(false)
  const [message, setMessage] = useState('')
  const [messageType, setMessageType] = useState('success') // 'success' | 'error'

  async function handleGenerateReport() {
    setReportLoading(true)
    setMessage('')
    
    try {
      console.log('🚀 Initiating report generation...')
      
      const response = await fetch('/api/generate-report', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          format: 'pdf',
          includeCharts: true,
          sections: [
            'Executive Summary',
            'Portfolio Overview',
            'Financial Metrics',
            'Project Progress',
            'AI Insights',
            'Risk Analysis',
            'Strategic Recommendations'
          ]
        })
      })
      
      const data = await response.json()
      
      if (data.success) {
        console.log('✅ Report generation successful:', data.report)
        
        // Save report to Emma KnowledgeBase
        try {
          const reportContent = `# ${data.report.title}

**Generated:** ${new Date(data.report.generatedAt).toLocaleString()}
**Format:** ${data.report.format}
**Confidentiality:** ${data.report.metadata.confidentiality}

---

## Executive Summary

${data.report.summary ? `
- **Total Projects:** ${data.report.summary.totalProjects}
- **Active Projects:** ${data.report.summary.activeProjects}
- **Completion Rate:** ${data.report.summary.completionRate}
- **Total Budget:** ${data.report.summary.totalBudget}
- **Projected ROI:** ${data.report.summary.projectedROI}
` : 'Summary data unavailable'}

---

## Sections Included

${data.report.sections.map(section => `- ${section}`).join('\n')}

---

## Report Details

This report was automatically generated by the AHK Strategic Command Center.

**Charts Included:** ${data.report.charts ? 'Yes' : 'No'}

---

*Report Version: ${data.report.metadata.version}*
`;

          const saveResponse = await fetch('/api/save-report', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({
              title: data.report.title,
              content: reportContent
            })
          });

          const saveData = await saveResponse.json();
          
          if (saveData.success) {
            console.log('💾 Report saved to archive:', saveData.filename);
            setMessage(`Report ready 🎉 - ${data.report.sections.length} sections, Saved to archive ✅`);
          } else {
            console.warn('⚠️ Report generated but not saved:', saveData.error);
            setMessage(`Report ready 🎉 - ${data.report.sections.length} sections (archive save failed)`);
          }
        } catch (saveError) {
          console.error('❌ Failed to save report:', saveError);
          setMessage(`Report ready 🎉 - ${data.report.sections.length} sections (archive save failed)`);
        }
        
        setMessageType('success')
        
        // Auto-clear message after 8 seconds
        setTimeout(() => setMessage(''), 8000)
      } else {
        console.error('❌ Report generation failed:', data)
        setMessage('Failed to generate report ❌')
        setMessageType('error')
      }
    } catch (error) {
      console.error('❌ Report generation error:', error)
      setMessage('Error generating report. Check console for details.')
      setMessageType('error')
    } finally {
      setReportLoading(false)
    }
  }

  async function handleRunAnalysis() {
    setAnalysisLoading(true)
    setMessage('')
    
    try {
      console.log('🤖 Initiating AI analysis...')
      
      // Log to API and get results
      const response = await fetch('/api/run-analysis', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          analysisType: 'full',
          trigger: 'dashboard-button'
        })
      })
      
      const data = await response.json()
      
      if (data.success) {
        console.log('✅ Analysis complete:', data.results)
        setMessage(`Analysis complete 🤖 - ${data.results.insights.length} insights, ${data.results.recommendations.length} recommendations`)
        setMessageType('success')
        
        // Then trigger the actual AI Co-Pilot panel
        window.dispatchEvent(new CustomEvent('runCoPilotAnalysis'))
        
        // Auto-clear message after 8 seconds
        setTimeout(() => setMessage(''), 8000)
      } else {
        console.error('❌ Analysis failed:', data)
        setMessage('Analysis failed ❌')
        setMessageType('error')
      }
    } catch (error) {
      console.error('❌ Analysis trigger error:', error)
      setMessage('Error running analysis. Check console for details.')
      setMessageType('error')
      
      // Still dispatch event even if logging fails
      window.dispatchEvent(new CustomEvent('runCoPilotAnalysis'))
    } finally {
      setAnalysisLoading(false)
    }
  }

  return (
    <div className="space-y-6 page-transition">
      {/* Feedback Message */}
      {message && (
        <div 
          className={`card animate-slide-in ${
            messageType === 'success' 
              ? 'bg-gradient-to-r from-green-50 to-emerald-50 border-2 border-green-500' 
              : 'bg-gradient-to-r from-red-50 to-rose-50 border-2 border-red-500'
          }`}
        >
          <div className="flex items-center justify-between">
            <p className={`font-semibold ${
              messageType === 'success' ? 'text-green-800' : 'text-red-800'
            }`}>
              {message}
            </p>
            <button 
              onClick={() => setMessage('')}
              className="text-gray-500 hover:text-gray-700 text-xl font-bold"
            >
              ×
            </button>
          </div>
        </div>
      )}

      {/* Page Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-display font-bold" style={{ color: 'var(--text-primary)' }}>
            Strategic Dashboard
          </h1>
          <p className="mt-1" style={{ color: 'var(--text-secondary)' }}>
            Your command center for AHK Strategies growth
          </p>
        </div>
        <button 
          onClick={handleGenerateReport}
          disabled={reportLoading}
          className="btn-primary disabled:opacity-50 disabled:cursor-not-allowed flex items-center space-x-2"
        >
          {reportLoading ? (
            <>
              <div className="animate-spin rounded-full h-4 w-4 border-b-2 border-white"></div>
              <span>Generating...</span>
            </>
          ) : (
            <span>Generate Report</span>
          )}
        </button>
      </div>

      {/* Key Metrics Grid */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <MetricCard
          title="Active Projects"
          value={overview.activeProjects}
          change="+1 this month"
          trend="up"
          icon={Rocket}
          color="navy"
        />
        <MetricCard
          title="Tasks Completed"
          value={`${overview.completedTasks}/${overview.totalTasks}`}
          change={`${Math.round((overview.completedTasks / overview.totalTasks) * 100)}%`}
          trend="up"
          icon={CheckCircle}
          color="gold"
        />
        <MetricCard
          title="Projected ROI"
          value={overview.projectedROI}
          change="+15% vs target"
          trend="up"
          icon={TrendingUp}
          color="slate"
        />
        <MetricCard
          title="Total Budget"
          value={overview.totalBudget}
          change="On track"
          trend="up"
          icon={DollarSign}
          color="navy"
        />
      </div>

      {/* Timeline Alert */}
      <div className="bg-gradient-to-r from-ahk-gold-500 to-ahk-gold-600 rounded-xl p-6 text-white shadow-lg">
        <div className="flex items-center justify-between">
          <div className="flex items-center space-x-4">
            <div className="bg-white bg-opacity-20 rounded-full p-3">
              <Clock className="w-6 h-6" />
            </div>
            <div>
              <h3 className="text-xl font-display font-bold">Next Milestone</h3>
              <p className="text-white text-opacity-90">
                {timeline.nextMilestone} - {timeline.daysToNextMilestone} days remaining
              </p>
            </div>
          </div>
          <div className="text-right">
            <p className="text-sm text-white text-opacity-80">Current Phase</p>
            <p className="text-lg font-bold">{timeline.currentPhase}</p>
          </div>
        </div>
      </div>

      {/* Projects Section */}
      <div>
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-2xl font-display font-bold text-ahk-navy-900">
            Active Projects
          </h2>
          <div className="flex items-center space-x-2 text-sm">
            <span className="flex items-center space-x-1">
              <span className="w-3 h-3 bg-green-500 rounded-full"></span>
              <span className="text-ahk-slate-600">{projectHealth.onTrack} On Track</span>
            </span>
            <span className="flex items-center space-x-1 ml-4">
              <span className="w-3 h-3 bg-blue-500 rounded-full"></span>
              <span className="text-ahk-slate-600">{projectHealth.planning} Planning</span>
            </span>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {projects.map((project) => (
            <ProjectCard key={project.id} project={project} />
          ))}
        </div>
      </div>

      {/* Quick Actions */}
      <div className="card">
        <h3 className="text-xl font-display font-bold text-ahk-navy-900 mb-4">
          Quick Actions
        </h3>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <button className="flex items-center space-x-3 p-4 border-2 border-ahk-slate-200 rounded-lg hover:border-ahk-navy-500 hover:bg-ahk-slate-50 transition-all">
            <Target className="w-6 h-6 text-ahk-navy-700" />
            <span className="font-semibold text-ahk-navy-900">Update Roadmap</span>
          </button>
          <button 
            onClick={handleRunAnalysis}
            disabled={analysisLoading}
            data-run-ai-analysis
            className="flex items-center space-x-3 p-4 border-2 border-ahk-slate-200 rounded-lg hover:border-ahk-gold-500 hover:bg-ahk-slate-50 transition-all cursor-pointer disabled:opacity-50 disabled:cursor-not-allowed"
          >
            {analysisLoading ? (
              <>
                <div className="animate-spin rounded-full h-6 w-6 border-b-2 border-ahk-gold-600"></div>
                <span className="font-semibold text-ahk-navy-900">Analyzing...</span>
              </>
            ) : (
              <>
                <TrendingUp className="w-6 h-6 text-ahk-gold-600" />
                <span className="font-semibold text-ahk-navy-900">Run AI Analysis</span>
              </>
            )}
          </button>
          <button className="flex items-center space-x-3 p-4 border-2 border-ahk-slate-200 rounded-lg hover:border-ahk-navy-500 hover:bg-ahk-slate-50 transition-all">
            <Rocket className="w-6 h-6 text-ahk-navy-700" />
            <span className="font-semibold text-ahk-navy-900">Export Report</span>
          </button>
        </div>
      </div>
    </div>
  )
}
